services:
  dns:
    image: article_dns
    container_name: article_dns
    build:
      context: .
      dockerfile: ./article_dns.Dockerfile
    ports:
      - 53
    networks:
      article_network:
        ipv4_address: 192.168.2.2
    hostname: ns1.example-domain.com

  client:
    image: article_client
    container_name: article_client
    build:
      context: .
      dockerfile: ./article_client.Dockerfile
    networks:
      article_network:
        ipv4_address: 192.168.2.3
    dns:
      - 192.168.2.2
    hostname: client.example-domain.com

  server1:
    image: article_server1
    container_name: article_server1
    build:
      context: .
      dockerfile: ./article_server1.Dockerfile
    ports:
      - 2525
    networks:
      article_network:
        ipv4_address: 192.168.2.4
    dns:
      - 192.168.2.2
    hostname: server-one.example-domain.com
  
  server2:
    image: article_server2
    container_name: article_server2
    build:
      context: .
      dockerfile: ./article_server2.Dockerfile
    ports:
      - 2625
    networks:
      article_network:
        ipv4_address: 192.168.2.5
    dns:
      - 192.168.2.2
    hostname: server-two.example-domain.com
  
  server3:
    image: article_server3
    container_name: article_server3
    build:
      context: .
      dockerfile: ./article_server3.Dockerfile
    ports:
      - 2625
    networks:
      article_network:
        ipv4_address: 192.168.2.6
    dns:
      - 192.168.2.2
    hostname: server-three.example-domain.com
  
  server4:
    image: article_server4
    container_name: article_server4
    build:
      context: .
      dockerfile: ./article_server4.Dockerfile
    ports:
      - 25
    networks:
      article_network:
        ipv4_address: 192.168.2.7
    dns:
      - 192.168.2.2
    hostname: server-four.example-domain.com

networks:
  article_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
